import React, { useEffect, useMemo, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { formatCurrency } from '@/lib/formatCurrency';
import { useNavigate } from 'react-router-dom';
import { Bell, ChevronRight, CreditCard, Eye, EyeOff, Heart, TrendingUp, Wallet } from 'lucide-react';

const maskAccount = (value = '') => { const d = String(value).replace(/\D/g, ''); return d.length >= 4 ? `•••• ${d.slice(-4)}` : '••••'; };

export default function Home() {
  const [user,setUser]=useState(null),[accounts,setAccounts]=useState([]),[cards,setCards]=useState([]),[portfolios,setPortfolios]=useState([]),[loading,setLoading]=useState(true),[hidden,setHidden]=useState(false);
  const navigate=useNavigate();
  useEffect(()=>{let cancelled=false;(async()=>{try{const me=await base44.auth.me();const [a,c,p]=await Promise.all([base44.entities.Account.filter({user_id:me.id},'-created_date').catch(()=>[]),base44.entities.PaymentCard.filter({user_id:me.id,status:'active'},'-created_date').catch(()=>[]),base44.entities.InvestmentPortfolio.filter({user_id:me.id},'-created_date').catch(()=>[])]);if(!cancelled){setUser(me);setAccounts(a);setCards(c);setPortfolios(p);}}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true;};},[]);
  const balance=useMemo(()=>accounts.reduce((s,a)=>s+(a.balance||0),0),[accounts]);
  const wealth=useMemo(()=>portfolios.reduce((s,p)=>s+(p.total_value||0),0),[portfolios]);
  const firstName=user?.full_name?.trim()?.split(/\s+/)?.[0]||'Member';
  const hour=new Date().getHours();const greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';
  if(loading)return <div className="min-h-screen flex items-center justify-center"><div className="w-8 h-8 border-2 border-brass/30 border-t-brass rounded-full animate-spin"/></div>;
  return <div className="px-5 pt-6 pb-28 max-w-[430px] mx-auto">
    <header className="flex items-start justify-between mb-7"><div><p className="text-gray text-sm">{greeting}</p><h1 className="text-3xl font-bold mt-1">{firstName}</h1><p className="text-gray text-sm mt-1">Your Vantoris relationship at a glance.</p></div><button onClick={()=>navigate('/messages')} className="w-11 h-11 rounded-full bg-white border border-border flex items-center justify-center"><Bell size={19}/></button></header>
    {cards.length>0?<div className="space-y-3 mb-7">{cards.map(card=><div key={card.id} className="relative overflow-hidden rounded-[30px] p-6 min-h-[205px] text-white shadow-2xl bg-gradient-to-br from-[#0A2140] via-[#12355D] to-[#07162A]"><div className="absolute -right-14 -top-14 w-44 h-44 rounded-full border border-brass/20"/><div className="flex justify-between"><span className="font-semibold tracking-[0.2em] text-sm">VANTORIS</span><CreditCard size={23} className="text-white/70"/></div><div className="mt-12 text-xl tracking-[0.23em]">•••• •••• •••• {card.last4}</div><div className="mt-7 flex justify-between"><div><p className="text-[9px] text-white/45 uppercase">Cardholder</p><p className="text-xs mt-1 uppercase">{card.cardholder_name||firstName}</p></div><div><p className="text-[9px] text-white/45 uppercase">Type</p><p className="text-xs mt-1 capitalize">{card.card_type||'debit'}</p></div></div></div>)}</div>:<button onClick={()=>navigate('/services')} className="w-full text-left rounded-[30px] bg-gradient-to-br from-[#0A2140] to-[#193D68] text-white p-6 mb-7 shadow-xl"><p className="text-xs uppercase tracking-[0.18em] text-white/50">Vantoris Card</p><h2 className="text-2xl font-semibold mt-2">Your card will live here</h2><p className="text-sm text-white/65 mt-2">Request an eligible card and it will appear on your Home.</p><span className="inline-flex items-center gap-1 text-sm font-semibold text-brass mt-5">View card services <ChevronRight size={16}/></span></button>}
    <section className="rounded-[28px] bg-white border border-border p-5 shadow-sm mb-5"><div className="flex justify-between items-center"><div><p className="text-xs uppercase tracking-[0.16em] text-gray">Available money</p><p className="text-3xl font-semibold mt-1">{hidden?'••••••':formatCurrency(balance)}</p></div><button onClick={()=>setHidden(v=>!v)} className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center">{hidden?<Eye size={18}/>:<EyeOff size={18}/>}</button></div><div className="mt-5 pt-4 border-t border-border/70 flex justify-between text-sm"><span className="text-gray">{accounts.length} account{accounts.length===1?'':'s'}</span><button onClick={()=>navigate('/move-money')} className="font-semibold text-brass">Manage money</button></div></section>
    {wealth>0&&<section className="rounded-[28px] bg-[#0B2342] text-white p-5 shadow-xl mb-5"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-white/50">Private wealth</p><h2 className="text-xl font-semibold mt-1">Portfolio</h2></div><TrendingUp size={20} className="text-brass"/></div><p className="text-3xl font-semibold mt-5">{hidden?'••••••':formatCurrency(wealth)}</p><p className="text-xs text-white/55 mt-1">Investment value across your portfolios</p><button onClick={()=>navigate('/investment')} className="mt-5 text-sm font-semibold text-brass">Open investments</button></section>}
    <section className="grid grid-cols-2 gap-3"><button onClick={()=>navigate('/move-money')} className="rounded-[24px] bg-white border border-border p-5 text-left shadow-sm"><Wallet size={21} className="text-brass"/><p className="font-semibold mt-4">Accounts & money</p><p className="text-xs text-gray mt-1">Send, receive, deposit and withdraw.</p></button><button onClick={()=>navigate('/herobox')} className="rounded-[24px] bg-white border border-border p-5 text-left shadow-sm"><Heart size={21} className="text-brass"/><p className="font-semibold mt-4">HeroBox</p><p className="text-xs text-gray mt-1">Support verified people and organizations.</p></button></section>
    <div className="mt-6 space-y-2">{accounts.slice(0,3).map(a=><div key={a.id} className="flex items-center justify-between rounded-2xl bg-white/70 px-4 py-3 text-sm"><span className="flex items-center gap-3"><Wallet size={16} className="text-gray"/><span>{a.account_name||a.account_type}<span className="block text-[11px] text-gray">{maskAccount(a.account_number)}</span></span></span><span className="font-semibold">{hidden?'••••':formatCurrency(a.balance||0)}</span></div>)}</div>
  </div>;
}
